application: helloworld
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt

- url: /.*
  script: hello_world.app

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

builtins:
- deferred: on
- remote_api: on
- appstats: off